services:
  - type: web
    name: ai-chat-app
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
    autoDeploy: true

databases:
  - name: postgres
    databaseName: ai_chat_db
    user: ai_chat_user